export const ROUND_REPOSITORY = "ROUND_REPOSITORY";
export const BET_REPOSITORY = "BET_REPOSITORY";
export const SEED_CHAIN_REPOSITORY = "SEED_CHAIN_REPOSITORY";
export const BET_SAGA_REPOSITORY = "BET_SAGA_REPOSITORY";
export const ROUND_LOOP_SERVICE = "ROUND_LOOP_SERVICE";
export const MULTIPLIER_BROADCAST_SERVICE = "MULTIPLIER_BROADCAST_SERVICE";
