export const ROUND_REPOSITORY = "ROUND_REPOSITORY";
export const BET_REPOSITORY = "BET_REPOSITORY";
export const SEED_CHAIN_REPOSITORY = "SEED_CHAIN_REPOSITORY";
export const BET_SAGA_REPOSITORY = "BET_SAGA_REPOSITORY";
