/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as FairRouteImport } from './routes/fair'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyRoundIdRouteImport } from './routes/verify.$roundId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const FairRoute = FairRouteImport.update({
  id: '/fair',
  path: '/fair',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoundIdRoute = VerifyRoundIdRouteImport.update({
  id: '/verify/$roundId',
  path: '/verify/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fair': typeof FairRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
  '/verify/$roundId': typeof VerifyRoundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fair': typeof FairRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
  '/verify/$roundId': typeof VerifyRoundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fair': typeof FairRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
  '/verify/$roundId': typeof VerifyRoundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fair'
    | '/landing'
    | '/login'
    | '/profile'
    | '/wallet'
    | '/verify/$roundId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fair'
    | '/landing'
    | '/login'
    | '/profile'
    | '/wallet'
    | '/verify/$roundId'
  id:
    | '__root__'
    | '/'
    | '/fair'
    | '/landing'
    | '/login'
    | '/profile'
    | '/wallet'
    | '/verify/$roundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FairRoute: typeof FairRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  WalletRoute: typeof WalletRoute
  VerifyRoundIdRoute: typeof VerifyRoundIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair': {
      id: '/fair'
      path: '/fair'
      fullPath: '/fair'
      preLoaderRoute: typeof FairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$roundId': {
      id: '/verify/$roundId'
      path: '/verify/$roundId'
      fullPath: '/verify/$roundId'
      preLoaderRoute: typeof VerifyRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FairRoute: FairRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  WalletRoute: WalletRoute,
  VerifyRoundIdRoute: VerifyRoundIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
