_format_version: "3.0"

services:
  - name: games-ws-service
    url: http://games:4101
    routes:
      - name: games-ws
        paths:
          - ~/ws/?$
        protocols:
          - http
          - https
        strip_path: false

  - name: games-service
    url: http://games:4001
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:3000
          methods:
            - GET
            - POST
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
          credentials: true
          max_age: 3600
    routes:
      - name: games-current
        paths:
          - ~/games/rounds/current$
        methods:
          - GET
          - OPTIONS
        strip_path: false
      - name: games-history
        paths:
          - ~/games/rounds/history$
        methods:
          - GET
          - OPTIONS
        strip_path: false
      - name: games-leaderboard
        paths:
          - ~/games/leaderboard$
        methods:
          - GET
          - OPTIONS
        strip_path: false
      - name: games-verify
        paths:
          - ~/games/rounds/[^/]+/verify$
        methods:
          - GET
          - OPTIONS
        strip_path: false
      - name: games-bets-me
        paths:
          - ~/games/bets/me$
        methods:
          - GET
          - OPTIONS
        strip_path: false
      - name: games-bet-place
        paths:
          - ~/games/bet$
        methods:
          - POST
          - OPTIONS
        strip_path: false
      - name: games-bet-cashout
        paths:
          - ~/games/bet/cashout$
        methods:
          - POST
          - OPTIONS
        strip_path: false

  - name: wallets-service
    url: http://wallets:4002
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:3000
          methods:
            - GET
            - POST
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
          credentials: true
          max_age: 3600
    routes:
      - name: wallets-provision
        paths:
          - ~/wallets$
        methods:
          - POST
          - OPTIONS
        strip_path: false
      - name: wallets-me
        paths:
          - ~/wallets/me$
        methods:
          - GET
          - OPTIONS
        strip_path: false
