_format_version: "3.0"

services:
  - name: games-service
    url: http://games:4001
    routes:
      - name: games-routes
        paths:
          - /games
        strip_path: true

  - name: wallets-service
    url: http://wallets:4002
    routes:
      - name: wallets-provision
        paths:
          - /wallets
        methods:
          - POST
        strip_path: true
      - name: wallets-me
        paths:
          - /wallets/me
        methods:
          - GET
        strip_path: true
