_format_version: "3.0"

services:
  - name: games-ws-service
    url: http://games:4101
    routes:
      - name: games-ws
        paths:
          - ~/ws/?$
        protocols:
          - http
          - https
        strip_path: false

  - name: games-service
    url: http://games:4001
    routes:
      - name: games-current
        paths:
          - ~/games/rounds/current$
        methods:
          - GET
        strip_path: false
      - name: games-history
        paths:
          - ~/games/rounds/history$
        methods:
          - GET
        strip_path: false
      - name: games-verify
        paths:
          - ~/games/rounds/[^/]+/verify$
        methods:
          - GET
        strip_path: false
      - name: games-bets-me
        paths:
          - ~/games/bets/me$
        methods:
          - GET
        strip_path: false
      - name: games-bet-place
        paths:
          - ~/games/bet$
        methods:
          - POST
        strip_path: false
      - name: games-bet-cashout
        paths:
          - ~/games/bet/cashout$
        methods:
          - POST
        strip_path: false

  - name: wallets-service
    url: http://wallets:4002
    routes:
      - name: wallets-provision
        paths:
          - ~/wallets$
        methods:
          - POST
        strip_path: false
      - name: wallets-me
        paths:
          - ~/wallets/me$
        methods:
          - GET
        strip_path: false
